### ISSUE TITLE
Update repo public URL

### ISSUE THREAD

**Issue by jgagne** [malmichaud/article-rework#3]
Please, update https://github.com/malmichaud/article-rework to https://malmichaud.github.io/article-rework

**Comment by malmichaud** [comment]
Thank you! I still see the older version with a gray background and red font. The one that comes up through Atom is a white background with all black font! How do I transfer the version from atom to github? I tried to make a commit change but it didnt work!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jgagne** [comment]
Try https://github.com/malmichaud/article-rework/issues/4

**Comment by jgagne** [comment]
And thanks for updating the URL.
