### ISSUE TITLE
Update main.css in css folder

### ISSUE THREAD

**Issue by jgagne** [malmichaud/article-rework#4]
Delete https://github.com/malmichaud/article-rework/blob/master/main.css, then upload the latest version of `main.css` into the`css` folder, overriding the older `main.css`. `index.html` is looking for `css/main.css` as the path.

**Comment by jgagne** [comment]
Update here: https://github.com/malmichaud/article-rework/blob/master/css/main.css

Then delete:
https://github.com/malmichaud/article-rework/blob/master/main.css

**Comment by malmichaud** [comment]
Im not sure what Im doing wrong, Wednesday before class time maybe we can meet so that I can share my screen with you and work out the issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jgagne** [comment]
Go to `main.css` and update with the folder `css` as hinted here: https://github.com/KirstieJane/STEMMRoleModels/wiki/Creating-new-folders-in-GitHub-repository-via-the-browser

Then delete: https://github.com/malmichaud/article-rework/blob/master/css
